baseURL = "https://starvingartistddllc.com/"
languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "Starving Artist Design & Development, L.L.C." 
    description = ""
    favicon = ""
    message = "COMING SOON!" 
    release = "September 1, 2024" 
    background = "" 

socialIcons = [      
    {name = "twitter", url = "https://twitter.com/kaethedev"},    
    {name = "facebook", url = "https://facebook.com/kaethedev"},    
    {name = "github", url = "https://github.com/kaethedev"},    
    {name = "instagram", url = "https://instagram.com/kaethedev"},    
    {name = "tiktok", url = "https://tiktok.com/kaethedev"},     
] 

[params.twitter]
	enable = true 
	username = "kaethedev"
